### ISSUE TITLE
CreateSession issue with ConfigurationOverrides

### ISSUE THREAD

**Issue by fredericcarre** [xcomponent/ReactiveXComponent.Net#79]
On public IXCSession CreateSession(ConfigurationOverrides configurationOverrides = null) method the folllowing code should use string.IsNullOrEmpty instead of null:
 if (configurationOverrides.Host != null)
            {
                busDetails.Host = configurationOverrides.Host;
            }

**Comment by anouarhassine** [comment]
That would introduce an issue for configuration elements we want to override with an empty string..
